# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('user', 'gcm_key')]),
        ),
    ]
