# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170130_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AddField(
            model_name='device',
            name='dev_id',
            field=models.CharField(default=b'2017-02-14 17:35:40.509234+00:00', max_length=50, unique=True, verbose_name=b'Device ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name=b'Is active?'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='reg_id',
            field=models.CharField(default=b'2017-02-14 17:36:01.405141+00:00', max_length=255, unique=True, verbose_name=b'Registration ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='device',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='device',
            name='gcm_key',
        ),
    ]
