# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:18
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import eulevo.models.package


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(
                    choices=[(1, b'aberto'), (2, b'concluido'), (3, b'rejeitado'), (4, b'cancelado'),
                             (5, b'finalizado')])),
                ('last_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'aberto'), (2, 'conclu\xeddo')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eulevo.Deal')),
                ('messages', models.ManyToManyField(related_name='contestmessages', through='eulevo.ContestMessage',
                                                    to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoneDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=10)),
                ('delivery_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('token_checked', models.BooleanField(default=False)),
                ('observation', models.CharField(max_length=140)),
                ('status', models.IntegerField(
                    choices=[(1, b'aguardando coleta'), (2, b'em viagem'), (3, b'entregue'), (4, b'finalizado'),
                             (5, b'contestado'), (6, b'deletado')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eulevo.Deal')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('weight_range', models.IntegerField(
                    choices=[(1, b'0 a 5kg'), (2, b'6 a 10kg'), (3, b'11 a 15kg'), (4, b'16 a 20kg'),
                             (5, b'mais de 20kg')])),
                ('destiny', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('delivery_until', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=eulevo.models.package.package_image_directory_path)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eulevo.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, b'remetente'), (2, b'viajante')])),
                ('rating', models.FloatField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eulevo.Deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_range', models.IntegerField(
                    choices=[(1, b'0 a 5kg'), (2, b'6 a 10kg'), (3, b'11 a 15kg'), (4, b'16 a 20kg'),
                             (5, b'mais de 20kg')])),
                ('destiny', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('vehicle_type', models.IntegerField(
                    choices=[(1, b'Carro de passeio'), (2, b'Caminhonete'), (3, b'Moto'), (4, 'Caminh\xe3o'),
                             (5, '\xd4nibus'), (6, 'Avi\xe3o'), (7, b'Navio')])),
                ('dt_travel', models.DateField()),
                ('blocked', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('deals', models.ManyToManyField(to='eulevo.Deal')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eulevo.Travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eulevo.Package'),
        ),
        migrations.AddField(
            model_name='deal',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eulevo.Travel'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestmessage',
            name='deal_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eulevo.DealContest'),
        ),
        migrations.AddField(
            model_name='contestmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'deal')},
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('package', 'travel')},
        ),
    ]
