# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eulevo', '0002_auto_20161210_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destiny_description',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='travel',
            name='destiny_description',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
