# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eulevo', '0004_remove_package_delivery_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
