# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eulevo', '0005_auto_20170201_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
